name: Publish Gradle Plugin

on:
  push:
    branches:
      - main        # snapshot builds
    tags:
      - 'v*'        # release builds

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Setup JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          server-id: ossrh  # Gradle publishing

      # 3. Import GPG key for signing
      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf

      # 4. Configure Gradle credentials
      - name: Configure Gradle properties
        run: |
          mkdir -p ~/.gradle
          echo "signing.gnupg.keyName=${{ secrets.GPG_KEY_ID }}" >> ~/.gradle/gradle.properties
          echo "signing.gnupg.passphrase=${{ secrets.GPG_PASSPHRASE }}" >> ~/.gradle/gradle.properties
          echo ${{ secrets.GRADLE_PUBLISH_KEY }} >> ~/.gradle/gradle.properties

      # 5. Build & publish
      - name: Publish Gradle Plugin
        run: |
          chmod +x ./gradlew
          if [[ "${{ steps.version.outputs.is_release }}" == "true" ]]; then
            echo "Publishing release version: ${{ steps.version.outputs.version }}"
            ./gradlew clean publishPlugins -Pversion=${{ steps.version.outputs.version }} --no-daemon --stacktrace
          else
            echo "Publishing snapshot version - $(date +%Y.%m.%d.%H%M%S)"
            ./gradlew clean publishPlugins -Pversion=$(date +%Y.%m.%d.%H%M%S) --no-daemon --stacktrace
          fi
